sudo: false
language: php
php:
  - 7.3

notifications:
  email: false

install:
  - composer install --dev --no-interaction
script:
  - ./vendor/bin/phpunit --configuration Tests/phpunit.xml
after_script:
  - travis_retry ./vendor/bin/php-coveralls
